sonata_admin:
    security:
        handler: sonata.admin.security.handler.noop
    dashboard:
        blocks:
            -
                position: top
                class: col-md-6
                type: sonata.admin.block.admin_list
            -
                position: bottom
                class: col-md-6
                type: sonata.block.service.text
                settings:
                    content: <div class="text-center"><a href="/terms-of-use">Terms of Use</a> | <a href="/privacy-policy">Privacy Policy</a></div>
        groups:
            Broadcasts:
                items:
                    - sonata.admin.livebroadcast
                    - sonata.admin.channel

sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.admin.block.search_result:
            contexts:   [admin]
        sonata.block.service.youtubeauth:
            contexts:   [admin]
        sonata.block.service.facebookauth:
            contexts:   [admin]
